# -*- coding: utf-8 -*-
lines = [
    '',
    '.btn-secondary {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: 6px;',
    '  padding: 8px 16px;',
    '  background: var(--surface);',
    '  color: var(--text-primary);',
    '  border: 0.5px solid var(--border);',
    '  border-radius: var(--radius-md);',
    '  font-size: 13px;',
    '  cursor: pointer;',
    '  transition: all 0.2s var(--ease);',
    '  font-family: inherit;',
    '}',
    '',
    '.btn-secondary:hover {',
    '  background: var(--surface-hover);',
    '}',
    '',
    '.btn-send {',
    '  width: 40px;',
    '  height: 40px;',
    '  border-radius: 50%;',
    '  background: linear-gradient(135deg, var(--accent), var(--accent-purple));',
    '  color: white;',
    '  border: none;',
    '  cursor: pointer;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  transition: all 0.2s var(--ease);',
    '  flex-shrink: 0;',
    '}',
    '',
    '.btn-send:hover {',
    '  transform: scale(1.05);',
    '  box-shadow: 0 4px 12px rgba(0,122,255,0.3);',
    '}',
    '',
    '.office-view {',
    '  max-width: 900px;',
    '  margin: 0 auto;',
    '}',
    '',
    '.stats-bar {',
    '  display: grid;',
    '  grid-template-columns: repeat(4, 1fr);',
    '  gap: 12px;',
    '  margin-bottom: 24px;',
    '}',
    '',
    '.stat-card {',
    '  background: var(--surface);',
    '  backdrop-filter: var(--glass-blur);',
    '  -webkit-backdrop-filter: var(--glass-blur);',
    '  border-radius: var(--radius-md);',
    '  padding: 16px;',
    '  box-shadow: var(--inner-highlight), var(--shadow-sm);',
    '  transition: all 0.2s var(--ease);',
    '}',
    '',
    '.stat-card:hover {',
    '  transform: translateY(-2px);',
    '  box-shadow: var(--inner-highlight), var(--shadow-md);',
    '}',
    '',
    '.stat-value {',
    '  font-size: 28px;',
    '  font-weight: 700;',
    '  color: var(--text-primary);',
    '}',
    '',
    '.stat-label {',
    '  font-size: 13px;',
    '  color: var(--text-secondary);',
    '  margin-top: 4px;',
    '}',
    '',
    '.section-title {',
    '  font-size: 16px;',
    '  font-weight: 600;',
    '  margin-bottom: 12px;',
    '  color: var(--text-primary);',
    '}',
    '',
    '.employee-grid {',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));',
    '  gap: 12px;',
    '  margin-bottom: 32px;',
    '}',
    '',
    '.employee-card {',
    '  background: var(--surface);',
    '  backdrop-filter: var(--glass-blur);',
    '  -webkit-backdrop-filter: var(--glass-blur);',
    '  border-radius: var(--radius-lg);',
    '  padding: 16px;',
    '  box-shadow: var(--inner-highlight), var(--shadow-sm);',
    '  cursor: pointer;',
    '  transition: all 0.25s var(--ease);',
    '}',
    '',
    '.employee-card:hover {',
    '  transform: translateY(-3px);',
    '  box-shadow: var(--inner-highlight), var(--shadow-lg);',
    '}',
    '',
    '.employee-card .emp-header {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  margin-bottom: 8px;',
    '}',
    '',
    '.employee-card .emp-avatar {',
    '  width: 40px;',
    '  height: 40px;',
    '  border-radius: 50%;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  font-weight: 700;',
    '  font-size: 16px;',
    '  color: white;',
    '  position: relative;',
    '  flex-shrink: 0;',
    '}',
    '',
    '.employee-card .emp-avatar::after {',
    "  content: '';",
    '  position: absolute;',
    '  inset: -3px;',
    '  border-radius: 50%;',
    '  background: inherit;',
    '  opacity: 0.25;',
    '  filter: blur(5px);',
    '  z-index: -1;',
    '}',
    '',
    '.employee-card .emp-name {',
    '  font-weight: 600;',
    '  font-size: 15px;',
    '}',
    '',
    '.employee-card .emp-role {',
    '  font-size: 12px;',
    '  color: var(--text-secondary);',
    '}',
    '',
    '.employee-card .emp-status {',
    '  font-size: 12px;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 4px;',
    '  margin-bottom: 8px;',
    '}',
    '',
    '.employee-card .emp-status .dot {',
    '  width: 6px;',
    '  height: 6px;',
    '  border-radius: 50%;',
    '}',
    '',
    '.employee-card .emp-status .dot.green {',
    '  background: var(--accent-green);',
    '  animation: pulse 2s infinite;',
    '}',
    '',
    '.employee-card .emp-status .dot.blue {',
    '  background: var(--accent);',
    '  animation: pulse 2s infinite;',
    '}',
    '',
    '.employee-card .emp-status .dot.gray {',
    '  background: var(--text-muted);',
    '}',
    '',
    '.employee-card .emp-task {',
    '  font-size: 12px;',
    '  color: var(--text-secondary);',
    '  padding: 6px 8px;',
    '  background: rgba(0,0,0,0.03);',
    '  border-radius: 8px;',
    '  margin-bottom: 8px;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '  white-space: nowrap;',
    '}',
    '',
    '.employee-card .emp-actions {',
    '  display: flex;',
    '  gap: 6px;',
    '}',
    '',
    '.employee-card .emp-actions button {',
    '  flex: 1;',
    '  padding: 6px 0;',
    '  border-radius: 8px;',
    '  font-size: 12px;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '  font-family: inherit;',
    '  border: 0.5px solid var(--border);',
    '  background: var(--