import os

def read_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()

# 读取 CSS
css_files = ['variables.css', 'components.css', 'layout.css', 'chat.css']
css_content = ''
for f in css_files:
    css_content += read_file('css/' + f) + '\n'

# 读取 JS
js_store = read_file('js/store.js')
js_ai = read_file('js/ai-gateway.js')

# 构建 HTML
parts = []
parts.append('<!DOCTYPE html>')
parts.append('<html lang="zh-CN">')
parts.append('<head>')
parts.append('  <meta charset="UTF-8">')
parts.append('  <meta name="viewport" content="width=device-width, initial-scale=1.0">')
parts.append('  <title>SoloBrave Office - AI 员工团队</title>')
parts.append('  <style>')
parts.append(css_content)
parts.append('  </style>')
parts.append('</head>')
parts.append('<body>')
parts.append('  <div id="app">')
parts.append('    <aside class="sidebar glass-panel" id="sidebar">')
parts.append('      <div class="sidebar-header">')
parts.append('        <div class="brand">')
parts.append('          <div class="brand-icon">🦞</div>')
parts.append('          <div class="brand-text">')
parts.append('            <span class="brand-name">SoloBrave</span>')
parts.append('            <span class="brand-tagline">AI 员工团队</span>')
parts.append('          </div>')
parts.append('        </div>')
parts.append('      </div>')
parts.append('      <nav class="employee-list" id="employee-list"></nav>')
parts.append('      <div class="sidebar-footer">')
parts.append('        <div class="api-status-card" id="api-status">')
parts.append('          <div class="status-indicator">')
parts.append('            <span class="status-dot"></span>')
parts.append('            <span class="status-text">未配置 API</span>')
parts.append('          </div>')
parts.append('          <button class="btn-config" onclick="window.location.href=\'lobster-office.html#settings\'">去配置 →</button>')
parts.append('        </div>')
parts.append('        <a href="lobster-office.html" class="admin-link"><span>🏢</span> 后台管理</a>')
parts.append('      </div>')
parts.append('    </aside>')
parts.append('')
parts.append('    <main class="chat-main" id="chat-main">')
parts.append('      <div class="chat-header glass-panel">')
parts.append('        <div class="chat-employee-info" id="chat-employee-info"></div>')
parts.append('        <div class="chat-actions">')
parts.append('          <button class="btn-icon" onclick="clearChat()">🗑️</button>')
parts.append('          <button class="btn-icon" onclick="toggleKnowledge()">📚</button>')
parts.append('        </div>')
parts.append('      </div>')
parts.append('      <div class="chat-messages" id="chat-messages"></div>')
parts.append('      <div class="chat-input-area glass-panel">')
parts.append('        <div class="input-wrapper">')
parts.append('          <textarea id="message-input" placeholder="和 AI 员工对话..." rows="1" onkeydown="handleInputKeydown(event)"></textarea>')
parts.append('          <button class="btn-send" onclick="sendMessage()">➤</button>')
parts.append('        </div>')
parts.append('        <div class="input-hints"><span>按 Enter 发送，Shift+Enter 换行</span></div>')
parts.append('      </div>')
parts.append('    </main>')
parts.append('  </div>')
parts.append('')
parts.append('  <script>')
parts.append(js_store)
parts.append(js_ai)
parts.append('  </script>')

# 添加内联 JS
parts.append('  <script>')
parts.append('  window.escapeHtml = function(t) {')
parts.append('    var d = document.createElement("div");')
parts.append('    d.textContent = t;')
parts.append('    return d.innerHTML;')
parts.append('  };')
parts.append('  </script>')

parts.append('  <script>')
parts.append('  window.renderEmployeeList = function() {')
parts.append('    var Store = window.SoloBraveStore;')
parts.append('    var list = document.getElementById("employee-list");')
parts.append('    if (!list) return;')
parts.append('    var employees = Store.get("employees") || [];')
parts.append('    var html = "";')
parts.append('    for (var i = 0; i < employees.length; i++) {')
parts.append('      var emp = employees[i];')
parts.append('      var activeClass = (window.currentEmployee && window.currentEmployee.id === emp.id) ? "active" : "";')
parts.append('      html += \'<div class="employee-card \' + activeClass + \'" onclick="selectEmployee(\'\' + emp.id + \'\')">\';')
parts.append('      html += \'<div class="employee-avatar" style="background: linear-gradient(135deg, \' + emp.gradient[0] + \' 0%, \' + emp.gradient[1] + \' 100%)">\' + emp.avatar + \'<span class="status-ring \' + emp.status + \'"></span></div>\';')
parts.append('      html += \'<div class="card-info"><div class="card-name">\' + emp.name + \'</div><div class="card-role">\' + emp.role + \'</div></div>\';')
parts.append('      html += \'</div>\';')
parts.append('    }')
parts.append('    list.innerHTML = html;')
parts.append('  };')
parts.append('  </script>')

parts.append('  <script>')
parts.append('  window.selectEmployee = function(employeeId) {')
parts.append('    var Store = window.SoloBraveStore;')
parts.append('    var employees = Store.get("employees") || [];')
parts.append('    for (var i = 0; i < employees.length; i++) {')
parts.append('      if (employees[i].id === employeeId) {')
parts.append('        window.currentEmployee = employees[i];')
parts.append('        break;')
parts.append('      }')
parts.append('    }')
parts.append('    renderEmployeeList();')
parts.append('    renderChatHeader();')
parts.append('    renderMessages();')
parts.append('  };')
parts.append('  </script>')

parts.append('  <script>')
parts.append('  window.renderChatHeader = function() {')
parts.append('    var header = document.getElementById("chat-employee-info");')
parts.append('    if (!header) return;')
parts.append('    if (!window.currentEmployee) {')
parts.append('      header.innerHTML = "<span>请选择一个员工开始对话</span>";')
parts.append('      return;')
parts.append('    }')
parts.append('    var emp = window.currentEmployee;')
parts.append('    header.innerHTML = \'<div class="employee-avatar" style="background: linear-gradient(135deg, \' + emp.gradient[0] + \' 0%, \' + emp.gradient[1] + \' 100%)">\' + emp.avatar + \'<span class="status-ring \' + emp.status + \'"></span></div><div class="employee-details"><span class="employee-name">\' + emp.name + \'</span><span class="employee-role">\' + emp.role + \' · \' + emp.personality + \'</span></div>\';')
parts.append('  };')
parts.append('  </script>')

parts.append('  <script>')
parts.append('  window.renderMessages = function() {')
parts.append('    var container = document.getElementById("chat-messages");')
parts.append('    if (!container) return;')
parts.append('    if (!window.currentEmployee) {')
parts.append('      container.innerHTML = "<div class=\"empty-state\"><div class=\"empty-icon\">SB</div><div class=\"empty-title\">Welcome</div><div class=\"empty-desc\">Select an AI employee</div></div>";